config/routes.rb
QuizRails::Application.routes.draw do
  get "front_end/question"
  get "front_end/answer"
  resources :quizzes

  root 'front_end#question'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  has_many :answers
  accepts_nested_attributes_for :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/front_end_controller.rb
class FrontEndController < ApplicationController
  def question
    @quiz = Quiz.order('random()').first
  end

  def answer
    @quiz = Quiz.find(params[:quiz_id])
    @answer = Answer.find(params[:answer_id])
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    3.times { @quiz.answers.build }
  end

  # GET /quizzes/1/edit
  def edit
    (3-@quiz.answers.size).times { @quiz.answers.build }
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quiz }
      else
        format.html { render action: 'new' }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:subject, :question, :image_url, answers_attributes: [:id, :text, :correct])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_end_helper.rb
module FrontEndHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/answers/_answer.html.erb
<p>
  <strong>Answer:</strong>
  <%= answer.text %> -
  <strong>Correct?</strong>
  <%= answer.correct %>
</p>

app/views/anwers/_answer.html.erb
<p>
  <strong>Answer:</strong>
  <%= answer.text %> -
  <strong>Correct?</strong>
  <%= answer.correct %>
</p>

app/views/front_end/_answer.html.erb
<div>
  <strong><%= link_to answer.text,
	      front_end_answer_path( { :quiz_id => @quiz.id, :answer_id =>  answer.id }),
	      {:class =>  "rispondi", "data-id" =>  answer.id } %>
  </strong>
</div>

app/views/front_end/answer.html.erb
<h1>
  <% if @answer.correct %>
  <font color="#7FFF00">Yo!!!
  <%= image_tag 'http://www.chicagonow.com/steve-dales-pet-world/files/2011/09/Happy-cat.jpg' %>
  <% else %>
  <font color="#DC143C">Loser!!
  <%= image_tag 'http://www.gazduna.com/wp-content/uploads/2012/01/man-with-l-for-loser_1.jpg' %>
  <% end %>
</h1>

app/views/front_end/question.html.erb
<h1><%= @quiz.subject %></h1>
<h2><%= @quiz.question %></h2>
<%= image_tag @quiz.image_url %>
<%= render partial: 'answer', collection: @quiz.answers %>
<%#= javascript_tag <<EOS
$(function() {
  $('.rispondi').click(function() {
    window.location = "/front_end/answer?quiz_id=#{ @quiz.id }&answer_id=" + event.target.data('id');
		       return false;

		       });
})
EOS
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizRails</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<footer>
  <div class="container">
    Rails Girls 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Quiz app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/quizzes">Quizzes</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>

  <%=f.fields_for :answers do |answer_form| %>
  <div>
    <%= answer_form.label 'Testo:' %>
    <%= answer_form.text_field :text %>
    <%= answer_form.label 'Corretta?:' %>
    <%= answer_form.check_box :correct %>
  </div>
  <% end %>


  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Listing quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Question</th>
      <th>Image url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.subject %></td>
        <td><%= quiz.question %></td>
        <td><%= quiz.image_url %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @quiz.subject %>
</p>

<p>
  <strong>Question:</strong>
  <%= @quiz.question %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag @quiz.image_url %>
</p>

<p>
  <%= render @quiz.answers %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>